apiVersion: apps/v1 
kind: Deployment
metadata:
  name: orders
  labels: 
     app: orders

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: 198937174082.dkr.ecr.us-east-1.amazonaws.com/orders:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1