version: '3.8'
services:
  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PRODUCTS_SERVICE_URL=http://products-service:8080
    depends_on:
      - products-service