FROM amazoncorretto:8
WORKDIR /app
COPY ./target/orders-service-example-0.0.1-SNAPSHOT.jar .
ARG URL_PAYMENTS
ARG URL_SHIPPING
ARG URL_PRODUCTS
ENV URL_PAYMENTS=$URL_PAYMENTS
ENV URL_SHIPPING=$URL_SHIPPING
ENV URL_SHIPPING=$URL_SHIPPING
EXPOSE 8081
CMD ["java", "-jar", "./orders-service-example-0.0.1-SNAPSHOT.jar", "$URL_PAYMENTS", "$URL_SHIPPING", "$URL_SHIPPING"]
