apiVersion: apps/v1 
kind: Deployment
metadata:
  name: orders
  labels: 
     app: orders

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: REPOSITORY_URI:TAG_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1