apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders
spec:
  
  selector:
    app: orders
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

  - type: LoadBalancer

  