apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: orders

 

  