apiVersion: v1
kind: Service
metadata:
  name: orders-service
  # annotations:
    # Asociar al Load Balancer existente
    ## Parametrizar
    ##service.beta.kubernetes.io/aws-load-balancer-arn: "arn:aws:elasticloadbalancing:REGION:ACCOUNT_ID:loadbalancer/LB_NAME"
    # Opcionales: configuraciones específicas del LB
    ##service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # O "elb" si es clásico
    ##service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-12345678"
    ##service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-12345678,subnet-87654321"
  labels:
    app: orders
spec:
  type: LoadBalancer
  selector:
    app: orders
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

  