name: api products testing
on:
    push:
        branches: [ "main" , "staging" , "develop", "feature/*"]
    pull_request:
        branches: [ "main" , "staging" , "develop" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Clone BackendProductsServiceExample
          run: git clone https://github.com/ObligatorioDevOps3M/BackendProductsServiceExample.git products-service

        - name: Set up JDK Corretto 8
          uses: actions/setup-java@v4
          with:
            java-version: '8'
            distribution: 'corretto'
            cache: maven

        - name: Build Products Service
          run: |
            cd products-service
            mvn -B package --file pom.xml

        - name: Build Orders Service
          run: mvn -B package --file pom.xml

        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

        - name: Build Docker images
          run: docker-compose build

        - name: Start services with Docker Compose
          run: docker-compose up -d

        - name: Wait for services to start
          run: |
            echo "Waiting for services to start..."
            sleep 30

        - name: Check if Orders Service is up
          run: |
            echo "Checking if Orders Service is up..."
            until curl -s -X POST -H "Content-Type: application/json" -d '["123", "321", "111"]' http://localhost:8081/orders; do
              echo "Waiting for Orders Service..."
              sleep 5
            done

        - name: Install Newman
          run: npm install -g newman

        - name: Run Newman tests
          run: newman run ./src/test/API_Orders.postman_collection.json

        - name: Stop services
          run: docker-compose down